import type { Metadata } from "next";
import { DEFAULT_LOCALE, LOCALES, type Locale, localizedHref } from "./i18n";

export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://production.gr";
export const SITE_NAME = "Production LTD";

/** Stable social share card (1200x630 PNG generated by /api/og). */
export const OG_IMAGE = "/api/og";
export const OG_IMAGE_DIMENSIONS = { width: 1200, height: 630 };

export const OG_LOCALE_MAP: Record<Locale, string> = {
  el: "el_GR",
  en: "en_US",
};

// Language-only hreflang. production.gr serves Greek plus an international
// English, so we avoid asserting a specific English region (was "en-US").
export const HREFLANG_MAP: Record<Locale, string> = {
  el: "el",
  en: "en",
};

export function buildLanguageAlternates(
  path: string,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const locale of LOCALES) {
    out[HREFLANG_MAP[locale]] = localizedHref(path, locale);
  }
  out["x-default"] = localizedHref(path, DEFAULT_LOCALE);
  return out;
}

/** OG locales for the locales OTHER than the current one. */
export function alternateOgLocales(locale: Locale): string[] {
  return LOCALES.filter((l) => l !== locale).map((l) => OG_LOCALE_MAP[l]);
}

type PageMetadataInput = {
  locale: Locale;
  title: string;
  description?: string;
  path: string;
  keywords?: string[];
  /**
   * When true, the title is used verbatim and bypasses the layout's
   * "%s — Production LTD" template (use for titles that already carry the
   * brand, e.g. the homepage, to avoid a doubled brand suffix).
   */
  titleAbsolute?: boolean;
};

export function pageMetadata({
  locale,
  title,
  description,
  path,
  keywords,
  titleAbsolute,
}: PageMetadataInput): Metadata {
  const canonicalPath = path.startsWith("/") ? path : `/${path}`;
  const canonical = localizedHref(canonicalPath, locale);
  // Mirror the rendered <title> (which gets the brand template) in the social
  // titles so OG/Twitter cards and the document title stay consistent.
  const socialTitle = titleAbsolute ? title : `${title} — ${SITE_NAME}`;

  return {
    title: titleAbsolute ? { absolute: title } : title,
    description,
    keywords,
    alternates: {
      canonical,
      languages: buildLanguageAlternates(canonicalPath),
    },
    openGraph: {
      title: socialTitle,
      description,
      url: canonical,
      siteName: SITE_NAME,
      type: "website",
      locale: OG_LOCALE_MAP[locale],
      alternateLocale: alternateOgLocales(locale),
      images: [{ url: OG_IMAGE, ...OG_IMAGE_DIMENSIONS, alt: SITE_NAME }],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: [OG_IMAGE],
    },
  };
}
